# --------------------------------------------------------------------.
# This command file was generated by paneldata.org                    .
# --------------------------------------------------------------------.
# !!! I M P O R T A N T - W A R N I N G !!!                           .
# You alone are responsible for contents and appropriate.             .
# usage by accepting the usage agreement.                             .
# --------------------------------------------------------------------.
# Please report any errors of the code generated here                 .
# to soepmail@diw.de                                                  .
# --------------------------------------------------------------------.


library("foreign")
### LOCAL VARIABLES ###
path_in <- "data/raw_data/raw/"
path_out <- "data/loaded_data/"


#* * * NOT PROCESSED * * *.


### LOAD [H|P]PFAD ###

pfad <- read.dta(file.path(path_in, "ppfad.dta"), convert.factors=F)
pfad <- pfad[ , c("bipop", "bbnetto", "bhhhnr", "zpop", "bbpop", "bihhnr", "bdhhnr", "bcpop", "bhnetto", "bgpop", "bdpop", "bepop", "bhpop", "bghhnr", "bdnetto", "persnr", "bbhhnr", "hhnr", "znetto", "sex", "bcnetto", "bfnetto", "gebjahr", "bahhnr", "bfhhnr", "bchhnr", "behhnr", "binetto", "bfpop", "zhhnr", "banetto", "benetto", "bgnetto", "psample", "bapop")]

### [UN]BALANCED ###

pfad <- with(pfad, pfad[ (bbnetto >= 10 & bbnetto < 20) | (binetto >= 10 & binetto < 20) | (benetto >= 10 & benetto < 20) | (bgnetto >= 10 & bgnetto < 20) | (bfnetto >= 10 & bfnetto < 20) | (znetto >= 10 & znetto < 20) | (bdnetto >= 10 & bdnetto < 20) | (bcnetto >= 10 & bcnetto < 20) | (bhnetto >= 10 & bhnetto < 20) | (banetto >= 10 & banetto < 20) , ])

### PRIVATE HOUSEHOLDS ###

pfad <- with(pfad, pfad[ (bbpop == 1 | bbpop == 2)| (bipop == 1 | bipop == 2)| (bepop == 1 | bepop == 2)| (bgpop == 1 | bgpop == 2)| (bfpop == 1 | bfpop == 2)| (zpop == 1 | zpop == 2)| (bdpop == 1 | bdpop == 2)| (bcpop == 1 | bcpop == 2)| (bhpop == 1 | bhpop == 2)| (bapop == 1 | bapop == 2), ])

### GENDER ( male = 1 / female = 2) ###

# all genders

### SORT [H|P]PFAD ###

# This is R -- no sorting neccessary :-)


### LOAD [H|P]HRF ###

hrf <- read.dta(file.path(path_in, "phrf.dta"), convert.factors=F)
hrf <- hrf[,c("bephrf", "zphrf", "bgphrf", "bfphrf", "persnr", "hhnr", "bbphrf", "prgroup", "bdphrf", "bhphrf", "biphrf", "bcphrf", "baphrf")]

### CREATE MASTER ###

master <- merge( pfad, hrf, by = c("persnr", "hhnr"))

### READ DATA ###

data <- list()


tmp_variables <- c("zh5201", "zhhnr")
tmp_dataset <- read.dta(file.path(path_in, "zh.dta"), convert.factors=F)
data[["zh"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("bch5101", "bchhnr")
tmp_dataset <- read.dta(file.path(path_in, "bch.dta"), convert.factors=F)
data[["bch"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("bahhnr", "bah5201")
tmp_dataset <- read.dta(file.path(path_in, "bah.dta"), convert.factors=F)
data[["bah"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("bfh4901", "bfhhnr")
tmp_dataset <- read.dta(file.path(path_in, "bfh.dta"), convert.factors=F)
data[["bfh"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("bghhnr", "bgh6801")
tmp_dataset <- read.dta(file.path(path_in, "bgh.dta"), convert.factors=F)
data[["bgh"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("beh5401", "behhnr")
tmp_dataset <- read.dta(file.path(path_in, "beh.dta"), convert.factors=F)
data[["beh"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("bbh5101", "bbhhnr")
tmp_dataset <- read.dta(file.path(path_in, "bbh.dta"), convert.factors=F)
data[["bbh"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("bhhhnr", "bhh_61_01")
tmp_dataset <- read.dta(file.path(path_in, "bhh.dta"), convert.factors=F)
data[["bhh"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("bdhhnr", "bdh5101")
tmp_dataset <- read.dta(file.path(path_in, "bdh.dta"), convert.factors=F)
data[["bdh"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("bihhnr", "bih_61_01")
tmp_dataset <- read.dta(file.path(path_in, "bih.dta"), convert.factors=F)
data[["bih"]] <- tmp_dataset[ , tmp_variables]

### MERGE ###

master <- merge(master, data[["zh"]], by = "zhhnr", all.x=T, all.y=F)
master <- merge(master, data[["bch"]], by = "bchhnr", all.x=T, all.y=F)
master <- merge(master, data[["bah"]], by = "bahhnr", all.x=T, all.y=F)
master <- merge(master, data[["bfh"]], by = "bfhhnr", all.x=T, all.y=F)
master <- merge(master, data[["bgh"]], by = "bghhnr", all.x=T, all.y=F)
master <- merge(master, data[["beh"]], by = "behhnr", all.x=T, all.y=F)
master <- merge(master, data[["bbh"]], by = "bbhhnr", all.x=T, all.y=F)
master <- merge(master, data[["bhh"]], by = "bhhhnr", all.x=T, all.y=F)
master <- merge(master, data[["bdh"]], by = "bdhhnr", all.x=T, all.y=F)
master <- merge(master, data[["bih"]], by = "bihhnr", all.x=T, all.y=F)

### DONE ###

attr(master, "label") <- "paneldata.org"
str(master)
save(master, file=file.path(path_out, "master_hh.RData"))