# --------------------------------------------------------------------.
# This command file was generated by paneldata.org                    .
# --------------------------------------------------------------------.
# !!! I M P O R T A N T - W A R N I N G !!!                           .
# You alone are responsible for contents and appropriate.             .
# usage by accepting the usage agreement.                             .
# --------------------------------------------------------------------.
# Please report any errors of the code generated here                 .
# to soepmail@diw.de                                                  .
# --------------------------------------------------------------------.


library("foreign")
### LOCAL VARIABLES ###
path_in <- "data/raw_data/raw"
path_out <- "data/loaded_data/"


#* * * NOT PROCESSED * * *.
# From datasets 'ddr18': ['sex'].


### LOAD [H|P]PFAD ###

pfad <- read.dta(file.path(path_in, "ppfad.dta"), convert.factors=F)
pfad <- pfad[ , c("bhnetto", "bfhhnr", "zpop", "zhhnr", "persnr", "bcpop", "bgpop", "gebjahr", "bhhhnr", "ypop", "bhpop", "yhhnr", "hhnr", "bgnetto", "bbhhnr", "bepop", "benetto", "bbpop", "znetto", "bdpop", "bahhnr", "ynetto", "bghhnr", "bcnetto", "psample", "bfpop", "bchhnr", "bapop", "bihhnr", "bdnetto", "bbnetto", "binetto", "sex", "bdhhnr", "banetto", "bipop", "bfnetto", "behhnr")]

### [UN]BALANCED ###

pfad <- with(pfad, pfad[ (bfnetto >= 10 & bfnetto < 20) | (banetto >= 10 & banetto < 20) | (bcnetto >= 10 & bcnetto < 20) | (binetto >= 10 & binetto < 20) | (ynetto >= 10 & ynetto < 20) | (bgnetto >= 10 & bgnetto < 20) | (benetto >= 10 & benetto < 20) | (bdnetto >= 10 & bdnetto < 20) | (znetto >= 10 & znetto < 20) | (bbnetto >= 10 & bbnetto < 20) | (bhnetto >= 10 & bhnetto < 20) , ])

### PRIVATE HOUSEHOLDS ###

pfad <- with(pfad, pfad[ (bfpop == 1 | bfpop == 2)| (bapop == 1 | bapop == 2)| (bcpop == 1 | bcpop == 2)| (bipop == 1 | bipop == 2)| (ypop == 1 | ypop == 2)| (bgpop == 1 | bgpop == 2)| (bepop == 1 | bepop == 2)| (bdpop == 1 | bdpop == 2)| (zpop == 1 | zpop == 2)| (bbpop == 1 | bbpop == 2)| (bhpop == 1 | bhpop == 2), ])

### GENDER ( male = 1 / female = 2) ###

# all genders

### SORT [H|P]PFAD ###

# This is R -- no sorting neccessary :-)


### LOAD [H|P]HRF ###

hrf <- read.dta(file.path(path_in, "phrf.dta"), convert.factors=F)
hrf <- hrf[,c("baphrf", "bephrf", "bdphrf", "bbphrf", "persnr", "yphrf", "prgroup", "bgphrf", "bfphrf", "bcphrf", "biphrf", "hhnr", "bhphrf", "zphrf")]

### CREATE MASTER ###

master <- merge( pfad, hrf, by = c("persnr", "hhnr"))

### READ DATA ###

data <- list()


tmp_variables <- c("bcp0103", "bcp129", "bcp7905", "f12p141b", "bcp7502", "bcp12705", "bcp12708", "bcp13", "bcp14", "bcp0108", "bcp91", "bcp12710", "bcp78", "bcp08", "bcp12704", "bcp12709", "bcp0102", "bcp12711", "bcp0110", "bcp93", "bcp12713", "bcp7401", "bcp151", "bcp12701", "bcp12706", "bcp7906", "bcp7402", "bcp0105", "bcp0104", "bcp12", "bcp76", "bcp15", "bcp0101", "bcp10401", "persnr", "bcp92", "bcp7907", "bcp0106", "bcp0107", "bcp18", "bcp139", "bcp12707", "bcpmonin", "bcp73", "bcp7501", "bcp12702", "bcp12801", "bcp0109")
tmp_dataset <- read.dta(file.path(path_in, "bcp.dta"), convert.factors=F)
data[["bcp"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("bgp10404", "bgp14805", "bgp14804", "bgp2601", "bgp106", "bgp10405", "bgp30", "bgp14808", "bgp13", "bgp0104", "bgp0103", "bgp14802", "bgp0110", "bgp14810", "bgp0105", "bgp0107", "bgp14807", "bgp14811", "bgp15401", "bgp38", "bgp0106", "bgp107", "bgp0102", "bgp0109", "bgp158", "bgp0108", "bgp28", "bgpsex", "bgp34", "bgp2602", "bgp14806", "bgp32", "bgp109", "bgp2701", "persnr", "bgp25", "bgpmonin", "bgp33", "bgp14812", "bgp14801", "bgp0101", "bgp105", "bgp10406", "bgp2702", "bgp175", "bgp35")
tmp_dataset <- read.dta(file.path(path_in, "bgp.dta"), convert.factors=F)
data[["bgp"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("zp8501", "zp12805", "zp9601", "zp15702", "zp89", "zp10", "zp12809", "zp0109", "zp130", "zp12811", "zp13", "zp12807", "zp8602", "zp87", "zp12901", "zp12806", "zp15701", "zp0106", "zp12808", "zp12", "zp0105", "zp0110", "zpmonin", "zp0108", "zp95", "zp0102", "zp12801", "zp2102", "zp0103", "zp0104", "zp16", "zp9005", "zp137", "zp9006", "zp0107", "persnr", "zp12804", "zp06", "zp2103", "zp8601", "zp12802", "zp11", "zp9004", "zp2101", "zp8502", "zp12810", "zp0101", "zp12812", "zp84")
tmp_dataset <- read.dta(file.path(path_in, "zp.dta"), convert.factors=F)
data[["zp"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("bhp_28_01", "bhp_27", "bhp_01_01", "bhp_29_01", "bhp_163", "bhp_186_07", "bhp_186_08", "bhp_29_02", "bhp_187", "bhp_06_01", "bhp_30", "bhp_186_11", "bhp_205", "bhp_421_q56", "bhp_186_05", "bhp_122_06", "bhp_158", "bhp_32", "bhp_36", "bhp_122_05", "bhp_186_04", "bhp_01_04", "bhp_01_06", "sex", "bhp_35", "bhp_01_05", "bhpmonin", "bhp_420_q56", "bhp_01_09", "bhp_01_10", "bhp_186_06", "persnr", "bhp_196", "bhp_186_01", "bhp_28_02", "bhp_37", "bhp_01_03", "bhp_186_13", "bhp_34", "bhp_186_02", "bhp_01_08", "bhp_01_07", "bhp_186_12", "bhp_122_04", "bhp_14", "bhp_01_02", "bhp_40")
tmp_dataset <- read.dta(file.path(path_in, "bhp.dta"), convert.factors=F)
data[["bhp"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("bbpmonin", "bbp9106", "bbp97", "bbp8601", "bbp13113", "bbp2103", "bbp06", "bbp13111", "bbp10", "bbp140", "bbp9105", "bbp0107", "bbp11", "bbp2102", "bbp8701", "bbp133", "bbp13201", "bbp13101", "bbp13107", "bbp13105", "bbp0108", "bbp12", "bbp8702", "bbp0105", "bbp88", "bbp90", "bbp15201", "bbp13104", "bbp0101", "bbp0110", "bbp10101", "bbp0104", "bbp13109", "bbp13106", "persnr", "bbp13", "bbp9107", "bbp2101", "bbp0102", "bbp0109", "bbp124", "bbp8602", "bbp85", "bbp15202", "bbp13108", "bbp13102", "bbp0103", "bbp0106", "bbp13110", "bbp16")
tmp_dataset <- read.dta(file.path(path_in, "bbp.dta"), convert.factors=F)
data[["bbp"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("bgj9703", "persnr")
tmp_dataset <- read.dta(file.path(path_in, "bgjugend.dta"), convert.factors=F)
data[["bgjugend"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("bip_45", "bip_123_06", "bip_46", "bip_05", "bipmonin", "bip_123_04", "bip_170_12", "bip_134", "bip_170_10", "bip_138", "bip_01_07", "bip_09_03", "bip_42", "bip_52_02", "bip_40", "bip_01_08", "bip_170_03", "bip_170_04", "bip_09_02", "bip_170_11", "bip_170_06", "bip_37", "bip_135", "bip_21", "bip_09_06", "bip_39_01", "bip_39_02", "bip_170_09", "bip_170_07", "bip_136", "bip_01_05", "bip_103", "bip_03", "bip_09_05", "bip_06", "bip_170_05", "bip_38_02", "bip_01_11", "bip_04_01", "bip_09_04", "bip_50", "bip_09_01", "bip_170_13", "bip_01_06", "bip_202_01", "bip_04_02", "bip_202_03", "bip_08_01", "bip_170_02", "bip_16", "bip_04_03", "bip_202_02", "bip_01_09", "bip_07", "bip_170_01", "bip_178", "bip_01_04", "bip_52_01", "bip_47", "bip_52_03", "bip_44", "persnr", "bip_38_01", "bip_01_03", "bip_01_02", "bip_01_01", "bip_191", "bip_170_08", "bip_123_05", "bip_01_10")
tmp_dataset <- read.dta(file.path(path_in, "bip.dta"), convert.factors=F)
data[["bip"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("bdp0110", "bdp3003", "bdp9301", "bdp13312", "bdp15802", "bdp0111", "bdp96", "bdp3001", "bdp06", "bdp11401", "bdp0105", "bdp04", "bdpm_p_46", "bdp155", "bdp0108", "bdp0102", "bdp0301", "bdp13311", "bdp15803", "bdp9706", "bdp15801", "bdpmonin", "bdp135", "bdp13302", "bdp0107", "bdp9302", "bdp110", "bdp19", "bdp13305", "bdp13308", "bdp13310", "bdp94", "bdp21", "bdp9705", "bdp0109", "bdp0303", "bdp0302", "bdp9202", "bdp3002", "bdp25", "persnr", "bdp13314", "bdp05", "bdp0101", "bdp13309", "bdp0106", "bdp13307", "bdp91", "bdp22", "bdp9707", "bdp20", "bdp143", "bdp13401", "bdp9201", "bdp13301", "bdp15", "bdp13306", "bdp0104", "bdp0103")
tmp_dataset <- read.dta(file.path(path_in, "bdp.dta"), convert.factors=F)
data[["bdp"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("yp13211", "yp13209", "yp0303", "yp99", "yp0104", "yp0108", "yp13207", "yp04", "yp0103", "yp9404", "yp88", "yp20", "yp0106", "yp05", "yp11", "yp9002", "yp0302", "yp8902", "yp23", "ypmonin", "yp101", "yp100", "yp14801", "yp15", "yp15503", "yp13205", "yp13201", "yp93", "yp9405", "yp0101", "yp15502", "yp0110", "yp0301", "yp9001", "yp22", "persnr", "yp0111", "yp21", "yp13210", "yp26", "yp91", "yp0102", "yp10901", "yp06", "yp13202", "yp13204", "yp13206", "yp13203", "yp149", "yp137", "yp0109", "yp0105", "yp9406", "yp8901", "yp15501")
tmp_dataset <- read.dta(file.path(path_in, "yp.dta"), convert.factors=F)
data[["yp"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("bap151", "bap0106", "bap87", "bap13012", "bap0102", "bap06", "bap13", "bap13009", "bap13007", "bap80", "bap7702", "bap7701", "bap78", "bap9801", "bap11", "bapmonin", "bap10", "bap75", "bap13002", "bap0109", "bap13001", "bap0110", "bap160", "bap13010", "bap135", "bap0107", "bap8107", "bap0104", "bap0105", "bap88", "bap8105", "bap0108", "persnr", "bap0103", "bap7601", "bap13005", "bap7602", "bap13008", "bap12", "bap89", "bap13006", "bap16", "bap8106", "bap0101", "bap15001", "bap13011", "bap13004")
tmp_dataset <- read.dta(file.path(path_in, "bap.dta"), convert.factors=F)
data[["bap"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("bfp0102", "bfp4203", "bfp14611", "bfp2701", "bfp36", "bfp14601", "bfp14602", "bfp4202", "bfp2702", "bfp39", "bfpmonin", "bfp158", "bfp4201", "bfp35", "bfp14610", "bfp14607", "bfp127", "bfp15", "bfp0107", "bfp26", "bfp14608", "bfp11805", "bfp0106", "bfpsex", "bfp31", "bfp0104", "bfp2801", "bfp174", "bfp0701", "persnr", "bfp14612", "bfp147", "bfp0105", "bfp0103", "bfp0110", "bfp0108", "bfp14605", "bfp14606", "bfp33", "bfp34", "bfp13101", "bfp11806", "bfp11804", "bfp29", "bfp2802", "bfp0109", "bfp14604", "bfp0101")
tmp_dataset <- read.dta(file.path(path_in, "bfp.dta"), convert.factors=F)
data[["bfp"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("bep19", "bep0105", "bep12306", "bep7902", "bep0106", "bep83", "bep0107", "bep12307", "bep129", "bep90", "bep89", "bep12308", "bep0108", "bep09", "bep8405", "bep7901", "bep14", "bep15", "bep16", "bep0103", "bep12309", "bepmonin", "bep0101", "bep13", "bep12301", "bep12311", "bep8406", "bep12304", "bep151", "bep127", "bep78", "bep8001", "bep12601", "bep9301", "bep12302", "persnr", "bep12310", "bep8002", "bep91", "bep8407", "bep0109", "bep81", "bep0102", "bep0104", "bep12305", "bep0110")
tmp_dataset <- read.dta(file.path(path_in, "bep.dta"), convert.factors=F)
data[["bep"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("bdj9203", "persnr")
tmp_dataset <- read.dta(file.path(path_in, "bdjugend.dta"), convert.factors=F)
data[["bdjugend"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("d1110108", "persnr", "d1110708")
tmp_dataset <- read.dta(file.path(path_in, "ypequiv.dta"), convert.factors=F)
data[["ypequiv"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("d1110114", "persnr", "d1110714")
tmp_dataset <- read.dta(file.path(path_in, "bepequiv.dta"), convert.factors=F)
data[["bepequiv"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("d1110710", "persnr", "d1110110")
tmp_dataset <- read.dta(file.path(path_in, "bapequiv.dta"), convert.factors=F)
data[["bapequiv"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("yj9003", "persnr")
tmp_dataset <- read.dta(file.path(path_in, "yjugend.dta"), convert.factors=F)
data[["yjugend"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("bbj9003", "persnr")
tmp_dataset <- read.dta(file.path(path_in, "bbjugend.dta"), convert.factors=F)
data[["bbjugend"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("persnr", "d1110712", "d1110112")
tmp_dataset <- read.dta(file.path(path_in, "bcpequiv.dta"), convert.factors=F)
data[["bcpequiv"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("d1110711", "persnr", "d1110111")
tmp_dataset <- read.dta(file.path(path_in, "bbpequiv.dta"), convert.factors=F)
data[["bbpequiv"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("bhp_04_02", "bhp_05", "bhp_04_01", "bhp_02", "bhp_03", "persnr")
tmp_dataset <- read.dta(file.path(path_in, "bhpluecke.dta"), convert.factors=F)
data[["bhpluecke"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("zj9003", "persnr")
tmp_dataset <- read.dta(file.path(path_in, "zjugend.dta"), convert.factors=F)
data[["zjugend"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("persnr", "d1110113", "d1110713")
tmp_dataset <- read.dta(file.path(path_in, "bdpequiv.dta"), convert.factors=F)
data[["bdpequiv"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("persnr", "bej9203")
tmp_dataset <- read.dta(file.path(path_in, "bejugend.dta"), convert.factors=F)
data[["bejugend"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("bhj_97_03", "persnr")
tmp_dataset <- read.dta(file.path(path_in, "bhjugend.dta"), convert.factors=F)
data[["bhjugend"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("d1110115", "persnr", "d1110715")
tmp_dataset <- read.dta(file.path(path_in, "bfpequiv.dta"), convert.factors=F)
data[["bfpequiv"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("persnr", "d1110716", "d1110116")
tmp_dataset <- read.dta(file.path(path_in, "bgpequiv.dta"), convert.factors=F)
data[["bgpequiv"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("d1110109", "d1110709", "persnr")
tmp_dataset <- read.dta(file.path(path_in, "zpequiv.dta"), convert.factors=F)
data[["zpequiv"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("bfj9203", "persnr")
tmp_dataset <- read.dta(file.path(path_in, "bfjugend.dta"), convert.factors=F)
data[["bfjugend"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("persnr", "baj9003")
tmp_dataset <- read.dta(file.path(path_in, "bajugend.dta"), convert.factors=F)
data[["bajugend"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("d1110117", "d1110717", "persnr")
tmp_dataset <- read.dta(file.path(path_in, "bhpequiv.dta"), convert.factors=F)
data[["bhpequiv"]] <- tmp_dataset[ , tmp_variables]


tmp_variables <- c("persnr", "bcj9203")
tmp_dataset <- read.dta(file.path(path_in, "bcjugend.dta"), convert.factors=F)
data[["bcjugend"]] <- tmp_dataset[ , tmp_variables]

### MERGE ###

master <- merge(master, data[["bcp"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["bgp"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["zp"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["bhp"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["bbp"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["bgjugend"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["bip"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["bdp"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["yp"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["bap"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["bfp"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["bep"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["bdjugend"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["ypequiv"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["bepequiv"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["bapequiv"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["yjugend"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["bbjugend"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["bcpequiv"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["bbpequiv"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["bhpluecke"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["zjugend"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["bdpequiv"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["bejugend"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["bhjugend"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["bfpequiv"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["bgpequiv"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["zpequiv"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["bfjugend"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["bajugend"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["bhpequiv"]], by = "persnr", all.x=T, all.y=F)
master <- merge(master, data[["bcjugend"]], by = "persnr", all.x=T, all.y=F)

### DONE ###

attr(master, "label") <- "paneldata.org"
str(master)
save(master, file=file.path(path_out, "master.RData"))